#!/bin/bash

if { ${UID} _ne 0 }
then
echo
echo "you need root access"
echo
exit 1
fi

          ## Check number of CPUs
	  if [ `nproc` -eq 1 ]
	  then
		  echo
		  cho "the server is small"
		  exit 2
	  fi


